services:
  postgres:
    image: postgres:16
    container_name: orchestrator-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orchestrator
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: orchestrator
      TZ: Europe/Warsaw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orchestrator -d orchestrator" ]
      interval: 5s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7-alpine
    container_name: orchestrator-redis
    command: [ "redis-server", "--appendonly", "yes", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # host clients
      - "29092:29092" # container clients
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # two listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL","kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
  model-api:
    image: model-api:latest
    environment:
      KAFKA_BROKERS: kafka:29092
      CONSUME_TOPIC: ml.predict.v1
      REPLY_TOPIC: ml.predict.replies.v1
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    healthcheck:
      test: "curl -fsS http://127.0.0.1:8000/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
#  orchestrator:
#    image: orchestrator:latest # local
#    container_name: orchestrator-app
#    restart: unless-stopped
#    depends_on:
#      - kafka
#    environment:
#      SPRING_PROFILES_ACTIVE: internal,external,admin,dev
#      DB_URL: jdbc:postgresql://postgres:5432/orchestrator
#      REDIS_URL: redis://redis:6379
#      MODEL_API_BASE_URL: http://model-api:8000
#      JWT_PRIVATE_KEY_LOCATION: file:/secrets/privKey.pem
#      JWT_PUBLIC_KEY_LOCATION: file:/secrets/pubKey.pem
#      FIREBASE_CREDENTIALS_LOCATION: file:/secrets/service-account.json
#    volumes:
#      - ./secrets:/secrets:ro
#    ports:
#      - "8080:8080"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

volumes:
  pgdata:
  redis-data: