services:
  postgres:
    image: postgres:16
    container_name: orchestrator-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orchestrator
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: orchestrator
      TZ: Europe/Warsaw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U orchestrator -d orchestrator" ]
      interval: 5s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7-alpine
    container_name: orchestrator-redis
    command: [ "redis-server", "--appendonly", "yes", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  model-api:
    image: poziomk3/model-api:v2.0.0
    ports:
      - "8000:8000"
    healthcheck:
      test: "curl -fsS http://127.0.0.1:8000/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
#  orchestrator:
#    image: orchestrator:latest # local
#    container_name: orchestrator-app
#    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: internal,external,admin,dev
#      DB_URL: jdbc:postgresql://postgres:5432/orchestrator
#      REDIS_URL: redis://redis:6379
#      MODEL_API_BASE_URL: http://model-api:8000
#      JWT_PRIVATE_KEY_LOCATION: file:/secrets/privKey.pem
#      JWT_PUBLIC_KEY_LOCATION: file:/secrets/pubKey.pem
#      FIREBASE_CREDENTIALS_LOCATION: file:/secrets/service-account.json
#    volumes:
#      - ./secrets:/secrets:ro
#    ports:
#      - "8080:8080"
volumes:
  pgdata:
  redis-data: