spring:
  application:
    name: external-orchestrator
model:
  api:
    base-url: http://localhost:8000
    api-key:
external-pairing:
  nonce-length: 32
  issuer: "hauth:orchestrator"
  audience:
    - "hauth:pairing"
